include                 mocha.conf

font_family             JetBrainsMono Nerd Font
font_size               16.0

cursor_shape            underline
cursor_blink_interval   0.4 ease-in-out

remember_window_layout  no
window_padding_width    10

background_opacity      0.8
