#     _          _                 _   _
#    / \   _ __ (_)_ __ ___   __ _| |_(_) ___  _ __  ___
#   / _ \ | '_ \| | '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
#  / ___ \| | | | | | | | | | (_| | |_| | (_) | | | \__ \
# /_/   \_\_| |_|_|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/
#
# -------------------------------------------------------

animations {
  enabled = yes

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  bezier = bouncy, 0.75, -0.20, 0.20, 1.25

  animation = windows, 1, 7, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, bouncy
  animation = layers, 1, 5, bouncy, slide
  animation = borderangle, 1, 30, default
}

layerrule = animation fade, match:namespace swaync-control-center
