#     _         _            _             _
#    / \  _   _| |_ ___  ___| |_ __ _ _ __| |_
#   / _ \| | | | __/ _ \/ __| __/ _` | '__| __|
#  / ___ \ |_| | || (_) \__ \ || (_| | |  | |_
# /_/   \_\__,_|\__\___/|___/\__\__,_|_|   \__|
#
# ---------------------------------------------

# 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/scripts/xdg.sh
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = xwaylandvideobridge

# Udiskie
exec-once = udiskie

# Hypridle
exec-once = hypridle

# Hyprplugins
exec-once = hyprpm update
exec-once = hyprpm enable hyprscrolling

# Theming
exec-once = ~/.config/scripts/gtkthemes.sh
exec-once = awww-daemon
exec-once = ~/.config/scripts/random-theme.sh

# 
exec-once = ~/.config/waybar/launch.sh
exec-once = swaync
exec-once = kdeconnect-indicator

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Apps
exec-once = openrgb --startminimized
exec-once = flatpak run com.spotify.Client
exec-once = flatpak run dev.vencord.Vesktop
