# __     __         _       _     _
# \ \   / /_ _ _ __(_) __ _| |__ | | ___  ___
#  \ \ / / _` | '__| |/ _` | '_ \| |/ _ \/ __|
#   \ V / (_| | |  | | (_| | |_) | |  __/\__ \
#    \_/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/

# Default programs
$terminal = alacritty
$fileManager = nautilus
$menu = wofi --show drun

# Monitors
$monitor1 = DP-1
$monitor2 = HDMI-A-1

# Some default env vars.
env = XCURSOR_SIZE, 24
env = QT_QPA_PLATFORMTHEME, qt5ct

# Colorscheme
source = ~/.config/hypr/mocha.conf


#  __  __             _ _
# |  \/  | ___  _ __ (_) |_ ___  _ __ ___
# | |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
# | |  | | (_) | | | | | || (_) | |  \__ \
# |_|  |_|\___/|_| |_|_|\__\___/|_|  |___/

monitor = $monitor1, preferred, 0x0, auto
monitor = $monitor2, preferred, 2560x0, auto, transform, 1


#  ___                   _
# |_ _|_ __  _ __  _   _| |_
#  | || '_ \| '_ \| | | | __|
#  | || | | | |_) | |_| | |_
# |___|_| |_| .__/ \__,_|\__|
#           |_|

input {
  kb_layout = pl
  numlock_by_default = true
}

device:logitech-g502-1 {
  sensitivity = -0.8
}


#  ____           _           _ _
# |  _ \__      _(_)_ __   __| | | ___
# | | | \ \ /\ / / | '_ \ / _` | |/ _ \
# | |_| |\ V  V /| | | | | (_| | |  __/
# |____/  \_/\_/ |_|_| |_|\__,_|_|\___|

dwindle {
  pseudotile = yes
  preserve_split = yes
}


# __        ___           _                            _
# \ \      / (_)_ __   __| | _____      __  _ __ _   _| | ___  ___
#  \ \ /\ / /| | '_ \ / _` |/ _ \ \ /\ / / | '__| | | | |/ _ \/ __|
#   \ V  V / | | | | | (_| | (_) \ V  V /  | |  | |_| | |  __/\__ \
#    \_/\_/  |_|_| |_|\__,_|\___/ \_/\_/   |_|   \__,_|_|\___||___/

windowrule = workspace 10, monitor $monitor2, class:(Spotify)
windowrule = workspace 9, monitro $monitor2, class:(discord)


# __        __         _                                          _
# \ \      / /__  _ __| | _____ _ __   __ _  ___ ___   _ __ _   _| | ___  ___
#  \ \ /\ / / _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \ | '__| | | | |/ _ \/ __|
#   \ V  V / (_) | |  |   <\__ \ |_) | (_| | (_|  __/ | |  | |_| | |  __/\__ \
#    \_/\_/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___| |_|   \__,_|_|\___||___/
#                              |_|

workspace = 9, monitor:$monitor2
workspace = 10, monitor:$monitor2


#     _         _            _             _
#    / \  _   _| |_ ___  ___| |_ __ _ _ __| |_
#   / _ \| | | | __/ _ \/ __| __/ _` | '__| __|
#  / ___ \ |_| | || (_) \__ \ || (_| | |  | |_
# /_/   \_\__,_|\__\___/|___/\__\__,_|_|   \__|

exec-once = waybar
exec-once = hyprpaper
exec-once = openrgb --startminimized
exec-once = dunst
exec-once=/usr/lib/polkit-kde-authentication-agent-1


source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/visual.conf
