#  _                      _            _
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   <
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|
#
# ------------------------------------------

# ------------------------------------------
# General
# ------------------------------------------
general {
  hide_cursor = true
}

# ------------------------------------------
# Colorscheme
# ------------------------------------------
source = ~/.config/hypr/colors.conf

# ------------------------------------------
# Variables
# ------------------------------------------
$monitor = DP-1
$wallpaper = ~/.config/hypr/wallpaper

# ------------------------------------------
# Background
# ------------------------------------------
background {
  path = $wallpaper

  blur_passes = 3
  blur_size = 5
}

# ------------------------------------------
# Input field
# ------------------------------------------
input-field {
  monitor = $monitor
  size = 250, 50
  outline_thickness = 0
  inner_color = $on_primary
  font_family = Fira Sans Semibold
  font_color = $on_background
  fade_on_empty = false
  
  position = 0, -600
  halign = center
  valign = center
}

# ------------------------------------------
# Clock
# ------------------------------------------
label {
  monitor = $monitor
  text = cmd[update: 60000] echo $(date +"%H:%M")
  color = $on_background
  font_family = Fira Sans Semibold
  font_size = 150

  position = 0, 500
  halign = center
  valign = center
}

# ------------------------------------------
# Date
# ------------------------------------------
label {
  monitor = $monitor
  text = cmd[update: 60000] echo $(date +"%A, %B %d")
  color = $on_background
  font_family = Fira Sans Semibold
  font_size = 40

  position = 0, 630
  halign = center
  valign = center
}

# ------------------------------------------
# Greeting
# ------------------------------------------
label {
  monitor = $monitor
  text = Hi, $USER
  color = $on_background
  font_family = JetBrainsMono Nerd Font
  font_size = 24

  position = 0, -550
  halign = center
}

# ------------------------------------------
# Song Info
# ------------------------------------------
label {
  monitor = $monitor
  text = cmd[update: 1000] ~/.config/hypr/scripts/hyprlock-song.sh
  color = $on_background
  font_family = Fira Sans Semibold
  font_size = 16

  position = 50, 0
  halign = left
  valign = center
}
