#  _                            _
# | |    __ _ _   _  ___  _   _| |_ ___
# | |   / _` | | | |/ _ \| | | | __/ __|
# | |__| (_| | |_| | (_) | |_| | |_\__ \
# |_____\__,_|\__, |\___/ \__,_|\__|___/
#             |___/
#
# ----------------------------------

general {
  layout = dwindle
}

# ----------------------------------
# Dwindle
# ----------------------------------
dwindle {
  pseudotile = true
  force_split = 2
  preserve_split = true
  special_scale_factor = 0.95
}

# ----------------------------------
# Master
# ----------------------------------
master {
  allow_small_split = true
  special_scale_factor = 0.95
}

# ----------------------------------
# Scrolling
# ----------------------------------
scrolling {
  column_width = 0.7
  fullscreen_on_one_column = true
}