#  _                            _
# | |    __ _ _   _  ___  _   _| |_
# | |   / _` | | | |/ _ \| | | | __|
# | |__| (_| | |_| | (_) | |_| | |_
# |_____\__,_|\__, |\___/ \__,_|\__|
#             |___/
#
# ----------------------------------

general {
  gaps_in = 5
  gaps_out = 20
  border_size = 2
  col.active_border = $blue $mauve 45deg
  col.inactive_border = $surface2

  cursor_inactive_timeout = 60000

  layout = dwindle

  allow_tearing = false
}


# ----------------------------------
# Dwindle
# ----------------------------------
dwindle {
  pseudotile = yes
  preserve_split = yes
}
