permission = /usr/bin/hyprshot, screencopy, allow
permission = /usr/bin/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = ${pkgs.xdg-desktop-portal-hyprland}/libexec/.xdg-desktop-portal-hyprland-wrapped, screencopy, allow
permission = ${lib.getExe config.programs.hyprlock.package}, screencopy, allow
