# __        ___           _                            _
# \ \      / (_)_ __   __| | _____      __  _ __ _   _| | ___  ___
#  \ \ /\ / /| | '_ \ / _` |/ _ \ \ /\ / / | '__| | | | |/ _ \/ __|
#   \ V  V / | | | | | (_| | (_) \ V  V /  | |  | |_| | |  __/\__ \
#    \_/\_/  |_|_| |_|\__,_|\___/ \_/\_/   |_|   \__,_|_|\___||___/
#
# -----------------------------------------------------------------

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

windowrule = match:class Spotify, workspace special:magic, no_initial_focus on
windowrule = match:class discord, workspace special:magic, no_initial_focus on
windowrule = match:class vesktop, workspace special:magic, no_initial_focus on
windowrule = match:class steam, float on
windowrule = match:title Steam, tile on
windowrule = match:class ^(steam_app)(.*), fullscreen on
windowrule = match:class org.kde.polkit-kde-authentication-agent-1, float on
windowrule = match:class org.gnome.FileRoller, float on
windowrule = match:class file-roller, float on
windowrule = match:class PureRef, float on
windowrule = match:class Aseprite, tile on
windowrule = match:class swaync, no_blur off
windowrule = match:class com.gabm.satty, float on
